### PR TITLE
#75 fixed broken validation of page_size parameter

### LINKED ISSUE #75: Impossible to save Rest Service in 1.10.2 - Problem with page size parameter
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.10.2

#### Summary

After upgrading from 1.9.0 to 1.10.2, I can no longer save the General Settings of a REST Service.

#### Current behavior

The PATCH request to `/api-tools/api/module/tms/rest/tms-V1-Rest-xxxxxxxxxx-Controller` fails with a 422 error, saying:
```
page_size: ["The Page Size must be either a positive integer or the value "-1" (disabling pagination)"]
```
The related fields from the request body are:
```
page_size: "50"
page_size_param: null
```
When switching back to 1.9.0, the problem disappears.

### PR DESCRIPTION
**Pull request by ppaulis**
Signed-off-by: Pascal Paulis <ppaulis@gmail.com>

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

This fixes the bug described in #75 .

The concerned part is:

if (is_numeric($value) && intval($value) !== $value) {
    return false;
}

This validation makes no sense the way it is, because the GUI sends strings like "50", and in this case `intval($value) !== $value` always evaluates to true, due to the strict comparison. Instead, the validation should be :
```
if (!is_numeric($value) || intval($value) != $value) {
    return false;
}
```
as proposed in this PR.

The Unit Test in this case was incorrect because it only tested on integers.

### CODE REVIEW

**Comment by ppaulis** [comment]
@froschdesign Here's the new PR with the commit correctly signed off and the fixed Unit Test.

**Comment by froschdesign** [comment]
@ppaulis 
> The Unit Test in this case was incorrect because it only tested on integers.

But this means that integers are valid and we need a test for this. Therefore, a new dataset needs to be added to the provider instead of changing existing ones.

**Comment by ppaulis** [comment]
@froschdesign I completed the tests, so that now all kinds of values are tested. I reorganized the code a little bit to avoid duplicated code fragments.

Here's a resume:
| value | return |
|---------|---------|
| '25' | valid | 
| '-1' | valid |
| 25 | valid |
| -1 | valid |
| 'string' | not valid |
| '25.5' | not valid |
| '-2' | not valid |
| 25.5 | not valid |
| -2 | not valid |

File: src/InputFilter/RestService/PatchInputFilter.php [hunk 1]
```diff
@@ -75,7 +75,7 @@ public function init()
             'continue_if_empty' => true,
             'validators'        => [
                 new CallbackValidator(function ($value) {
-                    if (is_numeric($value) && intval($value) !== $value) {
+                    if (!is_numeric($value) || intval($value) != $value) {
```
Comment (Ocramius) [inline src/InputFilter/RestService/PatchInputFilter.php]: This can be fixed without juggling types implicitly:

```php
if (! is_numeric($value) || ((string) $value) !== (string) (int) $value) {
```

Yes, I know the AST is a bit more complex, but the implicits of `!=` keep changing in PHP, so a strict comparison is preferred anyway.

Comment (ppaulis) [reply src/InputFilter/RestService/PatchInputFilter.php]: @Ocramius nice! And agreed, that's indeed better. PR is updated.

**Comment by weierophinney** [comment]
The CS and Psalm failures are due to an invalid lockfile; I'll fix that in a different PR and then we can rebase against that here.

File: src/InputFilter/RestService/PatchInputFilter.php [hunk 2]
```diff
@@ -75,7 +75,7 @@ public function init()
             'continue_if_empty' => true,
             'validators'        => [
                 new CallbackValidator(function ($value) {
-                    if (is_numeric($value) && intval($value) !== $value) {
+                    if (! is_numeric($value) || ((string) $value) !== (string) (int) $value) {
```
Comment (weierophinney) [inline src/InputFilter/RestService/PatchInputFilter.php:79]: I think we need a comment here indicating _why_ the casting is being done the way it is. At first glance, it looks like a mistake.

I almost wonder if this should be:

```
if (is_numeric($value) && intval($value) != $value) {
```

with a potential CS and/or Psalm rule suppression preceding, as what we're trying to determine is if we got an integer-ish value.

File: test/InputFilter/RestService/PatchInputFilterTest.php [hunk 3]
```diff
@@ -24,82 +24,18 @@ public function getInputFilter(): PatchInputFilter
         ]);
     }
 
-    /** @psalm-return array<string, array{0: array<string, mixed>}> */
+    /**
+     * @psalm-return array<string, array{
+     *     string|integer
+     * }>
+     */
```
Comment (weierophinney) [inline test/InputFilter/RestService/PatchInputFilterTest.php]:
```suggestion
    /** @psalm-return array<string, array{0: string|int}> */
```
This is more precise, and will give more information to Psalm.

File: test/InputFilter/RestService/PatchInputFilterTest.php [hunk 4]
```diff
@@ -198,10 +134,46 @@ public function dataProviderIsValidFalse(): array
 
     /**
      * @dataProvider dataProviderIsValidTrue
-     * @param array<string, mixed> $data
+     * @param mixed $pageSize
```
Comment (weierophinney) [inline test/InputFilter/RestService/PatchInputFilterTest.php]:
```suggestion
     * @param string|int $pageSize
```

This should match the provider.

File: test/InputFilter/RestService/PatchInputFilterTest.php [hunk 5]
```diff
@@ -224,4 +196,67 @@ public function testIsValidFalse(array $data, array $expectedInvalidKeys): void
         sort($testKeys);
         self::assertEquals($expectedInvalidKeys, $testKeys);
     }
+
+    /**
+     * @psalm-return array<string, array{
+     *     string|integer|float
+     * }>
+     */
```
Comment (weierophinney) [inline test/InputFilter/RestService/PatchInputFilterTest.php]:
```suggestion
    /** @psalm-return array<string, array{0: string|int|float}> */
```

File: test/InputFilter/RestService/PatchInputFilterTest.php [hunk 6]
```diff
@@ -224,4 +196,67 @@ public function testIsValidFalse(array $data, array $expectedInvalidKeys): void
...
+            'page_size-string-wrong-negative'  => ['-2'],
+            'page_size-string-nan'             => ['invalid'],
+            'page_size-float'                  => [25.5],
+            'page_size-integer-wrong-negative' => [-2],
+        ];
+    }
+
+    /**
+     * @dataProvider dataProviderInvalidPageSizes
+     * @param mixed $pageSize
```
Comment (weierophinney) [inline test/InputFilter/RestService/PatchInputFilterTest.php]:
```suggestion
     * @param string|int|float $pageSize
```

**Review by weierophinney — CHANGES_REQUESTED** [review]

File: test/InputFilter/RestService/PatchInputFilterTest.php (hunk 3 above)
Comment (ppaulis) [reply test/InputFilter/RestService/PatchInputFilterTest.php]: @weierophinney lack of experience with Psalm here. Thanks!

File: src/InputFilter/RestService/PatchInputFilter.php (hunk 2 above)
Comment (ppaulis) [reply src/InputFilter/RestService/PatchInputFilter.php:79]: @weierophinney I added a comment here to make things clearer. I think @Ocramius got a point here on not wanting to rely on a non-strict comparison. Let me know what you decide :-)

**Review by weierophinney — APPROVED** [review]
:ship:
